-- 018_cortex_sessions.sql
-- Cortex session history — lightweight JSONB storage for multi-turn chat memory.
-- Each row = one conversation session. History is an ordered array of exchanges.

CREATE TABLE IF NOT EXISTS cortex_sessions (
  id          TEXT PRIMARY KEY,           -- UUID generated by frontend
  history     JSONB NOT NULL DEFAULT '[]',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS cortex_sessions_updated_at ON cortex_sessions (updated_at DESC);
