#!/usr/bin/env bash
# install-git-hooks.sh — install the pre-commit conflict-marker guard into .git/hooks.
#
# Run this once per clone / fresh VPS checkout. The hook itself lives in
# scripts/pre-commit-guard.sh (version-controlled); .git/hooks/pre-commit is
# just a thin wrapper that calls it — so updates to the guard flow via git
# pulls without re-running this installer.

set -euo pipefail

# Resolve the repo root from this script's location so it works from anywhere.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
HOOK_TARGET="$HOOKS_DIR/pre-commit"
GUARD_SCRIPT_REL="backend/scripts/pre-commit-guard.sh"

# Some repos use this script from a non-backend/ layout (VPS ~/ecodiaos uses
# src/ directly, no backend/ prefix). Accept either layout.
if [ ! -f "$REPO_ROOT/$GUARD_SCRIPT_REL" ]; then
  if [ -f "$REPO_ROOT/scripts/pre-commit-guard.sh" ]; then
    GUARD_SCRIPT_REL="scripts/pre-commit-guard.sh"
  else
    echo "✖ install-git-hooks: cannot find pre-commit-guard.sh in $REPO_ROOT"
    exit 1
  fi
fi

mkdir -p "$HOOKS_DIR"

cat > "$HOOK_TARGET" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install-git-hooks.sh — calls the version-controlled
# guard so updates flow via git pulls. Edit the guard, not this file.
exec "\$(git rev-parse --show-toplevel)/$GUARD_SCRIPT_REL"
EOF

chmod +x "$HOOK_TARGET"
chmod +x "$REPO_ROOT/$GUARD_SCRIPT_REL"

echo "✓ pre-commit hook installed: $HOOK_TARGET"
echo "  → calls: $GUARD_SCRIPT_REL"
echo ""
echo "Test it:"
echo "  echo '<<<<<<< HEAD' > /tmp/conflict.txt"
echo "  git add /tmp/conflict.txt   # will be staged outside the repo, skip"
echo "Or trigger in-repo: add any file containing '<<<<<<< HEAD', 'git commit' should block."
